package com.company.tms.commons.constants.core;

public enum TestDataTypeConstants {

    WKDA_SOLD_PICKED("CAR_WKDA_SOLD_PICKED"),
    WKDA_SOLD_UNPAID("CAR_WKDA_SOLD_UNPAID"),
    WKDA_SOLD_PAID("CAR_WKDA_SOLD_PAID"),
    WKDA_PRICED("CAR_WKDA_PRICED"),
    WKDA_NOT_PRICED("CAR_WKDA_NOT_PRICED"),
    WKDA_PURCHASED("CAR_WKDA_PURCHASED"),
    NRI_INSPECTED("CAR_NRI_INSPECTED"),
    MSI_INSPECTED("CAR_MSI_INSPECTED"),
    MSI_WALK_IN_INSPECTED("CAR_MSI_WALK_IN_INSPECTED"), 

    VALID_PURCHASING("MERCHANT_VALID_PURCHASING"),
    A1_ADMIN_MERCHANT("A1_ADMIN_MERCHANT"),
    NRI_INSPECTOR("MERCHANT_NRI_INSPECTOR"),
    MERCHANT_DEFAULT("MERCHANT_DEFAULT"),
    
    MERCHANT_DE("AD_MERCHANT_DE"),
    RETAIL_DE("AD_RETAIL_DE"),
    RETAIL_NL("AD_RETAIL_NL"),
    RETAIL_ES("AD_RETAIL_ES"),
    RETAIL_BE("AD_RETAIL_BE"),
    RETAIL_IT("AD_RETAIL_IT"),
    RETAIL_FR("AD_RETAIL_FR"),
    RETAIL_AT("AD_RETAIL_AT"),
    RETAIL_SE("AD_RETAIL_SE"),
    RETAIL_PL("AD_RETAIL_PL"),
    IMPORTED_TO_RETAIL_DE("AD_IMPORTED_DE");

    private String value;

    TestDataTypeConstants(String value) {
        this.value = value;
    }

    public String value() {
        return this.value;
    }
}
