apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: database
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: database
    spec:
      containers:
      - image: mongo
        imagePullPolicy: ""
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: []
status: {}
