spring:
  application:
    name: tms
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/tms
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: on
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

server:
  port: 8181
logging:
  file:
    name: "${spring.application.name}.log"
